// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import TableOutlined from '/Users/wild/project/workspace/projects/laike-system/node_modules/.pnpm/registry.npmmirror.com+@ant-design+icons@4.8.1_biqbaboplfbrettd7655fr4n2y/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { TableOutlined };
