// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","name":"登录页","layout":false,"id":"1"},"2":{"path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/user-list","name":"用户管理","icon":"table","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/user-list/permission","name":"菜单权限配置","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/user-list/info","name":"新增/编辑用户","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/user-list/package","name":"套餐配置","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/","redirect":"/user-list","parentId":"ant-design-pro-layout","id":"7"},"8":{"path":"*","layout":false,"id":"8"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__UserList__index" */'@/pages/UserList/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__UserList__Permission__index" */'@/pages/UserList/Permission/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__UserList__Info__index" */'@/pages/UserList/Info/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__UserList__Package__index" */'@/pages/UserList/Package/index.tsx')),
'7': React.lazy(() => import( './EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/Users/wild/project/workspace/projects/laike-system/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
