// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import TableOutlined from '/Users/wild/project/workspace/projects/laike-system/node_modules/_@ant-design_icons@4.8.1@@ant-design/icons/es/icons/TableOutlined';
export default { TableOutlined };
