// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/wild/project/workspace/projects/laike-system/node_modules/_@umijs_renderer-react@4.0.80@@umijs/renderer-react';
export type {  History } from '/Users/wild/project/workspace/projects/laike-system/node_modules/_@umijs_renderer-react@4.0.80@@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/wild/project/workspace/projects/laike-system/node_modules/_umi@4.0.80@umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export const useServerInsertedHTML: Function = () => {};
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/Users/wild/project/workspace/projects/laike-system/src/.umi-production/plugin-access';
export { Provider, useModel } from '/Users/wild/project/workspace/projects/laike-system/src/.umi-production/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/wild/project/workspace/projects/laike-system/src/.umi-production/plugin-request';
// plugins types.d.ts
export * from '/Users/wild/project/workspace/projects/laike-system/src/.umi-production/plugin-access/types.d';
export * from '/Users/wild/project/workspace/projects/laike-system/src/.umi-production/plugin-antd/types.d';
export * from '/Users/wild/project/workspace/projects/laike-system/src/.umi-production/plugin-layout/types.d';
export * from '/Users/wild/project/workspace/projects/laike-system/src/.umi-production/plugin-request/types.d';
